#!/usr/bin/zsh

COST_PINEAPPLE=50
COST_BANANA=4
COST_WATERMELON=23
COST_BASKET=1

NBR_PINEAPPLE=1
NBR_BANANA=2
NBR_WATERMELON=3
NBR_BASKET=0

TOTAL=$(($COST_PINEAPPLE * $NBR_PINEAPPLE + $COST_BANANA * $NBR_BANANA + $COST_WATERMELON * $NBR_WATERMELON + $COST_BASKET * $NBR_BASKET))

echo "Total Cost is $TOTAL"